server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: Traefik-Sv-Monitoreo
  static_configs:
  - targets:
      - localhost
    labels:
      job: Traefik-Sv-Monitoreo
      host: Traefik-Sv-monitoreo
      __path__: /opt/dockerfiles/monitoreo/traefik-front-certs/logs/*.log
